os: linux
dist: bionic

language: python
cache: pip
python: 3.7

env:
  global:
    - PASS_VERSION=1.7.3
  jobs:
    - TEST_MAGIC=file-magic
    - TEST_MAGIC=python-magic

addons:
  apt:
    packages:
      - gnome-keyring
      - libsodium23

install:
  - export PREFIX=$HOME/.bin/usr PATH="$PATH:$HOME/.bin/usr/bin"
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-$PASS_VERSION.tar.xz
  - tar -xf password-store-$PASS_VERSION.tar.xz
  - make --directory=password-store-$PASS_VERSION install
  - mkdir -p ~/.local/share/keyrings/
  - echo '#!/usr/bin/env bash\necho lpass' > $HOME/.bin/usr/bin/lpass
  - sudo chmod 755 $HOME/.bin/usr/bin/lpass
  - cp tests/assets/db/gnome-keyring.keyring ~/.local/share/keyrings/pass-import.keyring
  - cp tests/assets/sphinx.cfg ~/.sphinxrc
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libsodium.so.23 /usr/lib/x86_64-linux-gnu/libequihash.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libsodium.so.23 /usr/lib/x86_64-linux-gnu/libsphinx.so
  - sudo ldconfig
  - pip3 install --upgrade pip
  - pip3 install green coverage codacy-coverage pyaml defusedxml cryptography pykeepass secretstorage pwdsphinx $TEST_MAGIC
  - sphinx init

script:
  - dbus-run-session -- make tests

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email: false
